apiVersion: v1
kind: Service
metadata:
  name: dev-in-cluster-db
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubernetes.io/service-name: "dev-in-cluster-db"
spec:
  selector:
    app: dev-db-pg
  ports:
    - port: 5432

