---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: jungschi-dev
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgAm1ei99i/0YOiFrP/EW7KWp6VYJMLAu51GkY/SRgkKxD4YA6UkA0X78uk0yet9Ee/0htgcIFx339fTaqF3AUrUYBKubg9FcI3P1FMxbaYv8fORydM0b5noAA11guMb0zza162I5IN9qMtryoP2dTO9S3uWj535nTLFGswaqWMAM7Qx7AVrR8046TdT96NDG7/XS+b980RZuKtur4iVqlmiKY+Wcpbf7kFdyI0Yj1zGyN6T5wQW1wrMWi6UcYBu1cmv+fKd8aqsvJtAiu1bHeE2FH5ImGfAgkDQfNZig5xUj/z7xJMK+BOQ63WtbAWL8FZurUV/rTyfVgL3a4jrMUBusb1PD3bYJqhxwgZHPqrkQZcISU+vrSzZsDBBDUDfqGPIuGdvUO5hlIy5u6wyXjw+bGIRbaBEcrHCx+JpgkJsAsi6jDNKYMb6/F0cnVc0TkE59A9euCVEnqnpIuqxK0ekpM3ul1hpyCSLUQBj+gvDKY4mE5y9Dt0J1SJu2bSTFD748IRqxoKf4kKcDUUwzPZ2SACrbQqha/QCYGQpe/FufqJj7tN/6hsXS8m89hJxBq8sPArxZ25vqcvZEWQUOkNOM0QlcB7POxeL3KpNNxKjUcLJNd10y9OKTNXd7Dn4ADNse8+EMpuHkwhXvSxf7kvO6Ev2yQ7vfeOO6zvyxYnQTZVVThIEplkG1EaXP+IUaPvj8Vd8gh5XLO/l5l1/0CyxxrCwqNuhTHay10qkBn7cFA==
  template:
    metadata:
      name: keycloak
      namespace: jungschi-dev
    type: Opaque
