---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: jungschi-dev
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgABrg4YGlcMGmOJeubkwKATni0cHYQPSlu7o05JW3iR/Q7VAjSytP0Pm+OqpXOs8S3oiY3VQWPLxzMLiL3zUoHxF9tz0de960cr+U5SDG9LOTULbNC8L3kKstd/lWfWV8nqDTnI0BBBt3tnV0QAxOlbS2QUQvL2o4RrdTTON2IN9+0w8UqUC3D+746Kwow2j02xFHUyoTDLhUObUlfnxgKBUUhtxuU6ASI3KHuQFpp3ezWxMNJQe9uRAOi5GFckskF2vuJKNl7ljDLwcpIxWJeZ7LfTnCSO7GEQOh1t0+nEJqO+P/sW3Owdc5XIYK7/r9kGKQ4+yiJORd21w/0kpYAb3pnqpKpmjbVGW+l74lum2omCUEq+1LJppQXU9J8wMohiKxHQ9fledNy5TIOKbefJ5kediTBCBqAG9zjf8XIh+3N/XuzoWn5JKdRGZCNo81GjEJNhSZIZg/RSpZUNn0kuXFiWZPjzqK3GM/CDkGICe9Ex18gnrJAeTjwv8l2zPcCRpmTeSjI4b8lC09N4izQJCgqfITbxNIHQiTgdKxvbzEUc+e7dd8FSQPPU+nCqquFjqWCuB/+SMzwgbwsBlOkAM313MJ0c4ajFMnQ0McT3H2IwULUjCBuam2nj9w2dQrr63KBIZ8RsF1EvUQIt8cQCUwZuHnHboM1BeRnQusD4WTrwq98AXuQ2kJhXWxvbcgN1r8zl9IORKv0ScpP0xTY7a7abVNED010uhv9M+ZBbeA==
  template:
    metadata:
      name: keycloak
      namespace: jungschi-dev
    type: Opaque
