kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - name: jungschi-back
    newName: ghcr.io/denic0la/jungschi-back
    newTag: v2.1.0
  - name: jungschi-ui
    newName: ghcr.io/denic0la/jungschi-ui
    newTag: v2.1.1


resources:
  - ../base
  - ingress.yaml
  - sealedsecret_database-config.yaml
  - sealedsecret_keycloak.yaml

configMapGenerator:
  - files:
      - application-prod.yaml
    name: application-config
  - files:
      - nginx.conf
    name: nginx-config


#patches:
#  - path: patch-stop-all.yaml
#    target:
#      kind: Deployment
