---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: jungschi
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgA8gOx3tt2edlQJQlBhMkdNsnUTCRb3EOlxRdhMCHlodYEe1IcjsNfrTSTW/EuSx+tUy1UnOukvhA8Zz7biWxPfN90x/OivhDVGGnGcr+U5cMYWnqIH+1jKFBEO1+pqJ48Vzdn8VJXJat1CzhvWaOBJmRqo2+aGWZa9GnO5E6mFO4n9TDe/PAYZ+JBistXeY3UVbdFhI+j5QkIPQuyVJdb/TQn8d0kq4B6Ph3wA6pQ75xiA6D7ya/1EBxO4Hof9kZQSgQHeBsEOLL0NynIUTU4N9jmbD0DZuLTLL1IBdwW7iLvYrNNR9f4zHkO5hnjPjc31pG+rUS3ZmrYzk+OfQbD+bbB0TSlmwa5GPY3gEWo+zbYsCw70llYMvCzK0RfsT4Tr87bXsfKqOWmgfFKBnH1LXBxZYc/qu5IEylWC/J52g6jLc/SKuhMlSpkA+t8P/Kd4PMSS52fRpEkgzm1VHJLZPQjGVCjwPNOIGuf1NXJWwqdXmDwsowqso+f04iwprAEyp/epNFSWgY1ivryUqp3Hb2J/cCciDvYGE0/SoKBl+FtIF76j9PXNCBrPQ/hcOg+NpDwyCVIpQQdRk4aN315Vm9TfsOLEKWRVDBrarLpdZuiwJ9znVXtyqPSltKJUAaN4Ix6Oc746oDRMz4FB+Qa9IstHOaWhsqLr6kv36dn3UCbl+9+WzTg4PQLw663AusgJUNycqJ6+B0ZGUYwbPLUFaGHQwjsxrytLpsYsuyaoog==
  template:
    metadata:
      name: keycloak
      namespace: jungschi
    type: Opaque
